volumes:
  lb_local_data:

services:
  lb_local:
    build: .
    image: listenbrainz-local
    ports:
      - "${DOMAIN}:${PORT}:3031"
    volumes:
      - lb_local_data:/data:z
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - AUTHORIZED_USERS=${AUTHORIZED_USERS}
      - DOMAIN=${DOMAIN}
      - PORT=${PORT}
      - MUSICBRAINZ_CLIENT_ID=${MUSICBRAINZ_CLIENT_ID}
      - MUSICBRAINZ_CLIENT_SECRET=${MUSICBRAINZ_CLIENT_SECRET}
      - DATABASE_FILE=/data/lb-local.db
