volumes:
  lb_local_data:

services:

  web:
    build: .
    image: listenbrainz-local
    expose:
      - "3031"
    volumes:
      - lb_local_data:/data:z
    restart: unless-stopped
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_USERS=${ADMIN_USERS}
      - DOMAIN=${DOMAIN}
      - PORT=${PORT}
      - MUSICBRAINZ_CLIENT_ID=${MUSICBRAINZ_CLIENT_ID}
      - MUSICBRAINZ_CLIENT_SECRET=${MUSICBRAINZ_CLIENT_SECRET}
      - DATABASE_FILE=/data/lb-local.db
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}

networks:
  default:
    name: nginx-proxy
