volumes:
  lb_local_data:
  html:
  vhostd:
  certs:

services:

  web:
    build: .
    image: listenbrainz-local
    expose:
      - "3031"
    volumes:
      - lb_local_data:/data:z
    restart: unless-stopped
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - AUTHORIZED_USERS=${AUTHORIZED_USERS}
      - DOMAIN=${DOMAIN}
      - PORT=${PORT}
      - MUSICBRAINZ_CLIENT_ID=${MUSICBRAINZ_CLIENT_ID}
      - MUSICBRAINZ_CLIENT_SECRET=${MUSICBRAINZ_CLIENT_SECRET}
      - DATABASE_FILE=/data/lb-local.db
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}

  nginx:
    image: jwilder/nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
        
  le:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - html:/usr/share/nginx/html
    environment:
      - NGINX_PROXY_CONTAINER=nginx
