services:
  lb_local:
    build: .
    image: listenbrainz-local
    ports:
      - "127.0.0.1:8000:3031"
    volumes:
      - .:/code/lb-local:z
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_USERS=${ADMIN_USERS}
      - DOMAIN=${DOMAIN}
      - MUSICBRAINZ_CLIENT_ID=${MUSICBRAINZ_CLIENT_ID}
      - MUSICBRAINZ_CLIENT_SECRET=${MUSICBRAINZ_CLIENT_SECRET}
